# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use the official Node.js image as a build environment
FROM node:18-alpine AS build

# Install pnpm globally
RUN npm install -g pnpm

# Set the working directory
WORKDIR /app

# Copy package.json and pnpm-lock.yaml files to the working directory
COPY package.json pnpm-lock.yaml ./

# Install dependencies
RUN pnpm install

# Copy the rest of the application files
COPY . .

# Build the application
RUN pnpm run build

# Use a lighter Node.js image for the final image
FROM node:18-alpine

# Set the working directory
WORKDIR /app

# Copy the build from the previous stage
COPY --from=build /app/build /app/build
COPY --from=build /app/package.json /app/package.json
COPY --from=build /app/pnpm-lock.yaml /app/pnpm-lock.yaml
COPY --from=build /app/node_modules /app/node_modules

# Set environment variables (assuming you'll provide them during container runtime)
# ENV SERPER_API_KEY=your_api_key_here

# Specify the command to run the application
ENTRYPOINT ["node", "build/index.js"]
